/** Declaration file generated by dts-gen */

export function defaultErrorHandler(error: Error): void;

export default function acall(
  value: Function | Promise<any> | any,
  errorHandler: (error: Error) => void
): Promise<any>;
